name: dockerfile-build
on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Dockerfile
        run: docker build -t tsugi-dockerfile-build .
